extends: .eslintrc.base.yml
parser: babel-eslint
plugins:
  - flowtype
rules:
  # `eslint-plugin-flowtype` rule list based on `v4.2.x`
  # https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype

  flowtype/array-style-complex-type: [error, verbose]
  flowtype/array-style-simple-type: [error, verbose]
  flowtype/define-flow-type: error
  flowtype/newline-after-flow-annotation: [error, always]
  flowtype/no-dupe-keys: error
  flowtype/no-existential-type: off # checked by Flow
  flowtype/no-flow-fix-me-comments: off # TODO
  flowtype/no-mixed: off
  flowtype/no-mutable-array: off
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-unused-expressions: off
  flowtype/no-weak-types: [error, { any: false }]
  flowtype/require-compound-type-alias: off
  flowtype/require-exact-type: off # TODO
  flowtype/require-indexer-name: error
  flowtype/require-inexact-type: off # checked by Flow
  flowtype/require-parameter-type: off
  flowtype/require-readonly-react-props: off
  flowtype/require-return-type: off
  flowtype/require-types-at-top: off
  flowtype/require-valid-file-annotation:
    [error, always, { annotationStyle: line, strict: true }]
  flowtype/require-variable-type: off
  flowtype/sort-keys: off
  flowtype/spread-exact-type: off
  flowtype/type-id-match: [error, '^[A-Z]']
  flowtype/type-import-style: [error, identifier, { ignoreTypeDefault: true }]
  flowtype/use-flow-type: error

  # Bellow rules are disabled because coflicts with Prettier, see:
  # https://github.com/prettier/eslint-config-prettier/blob/master/flowtype.js
  flowtype/boolean-style: off
  flowtype/delimiter-dangle: off
  flowtype/generic-spacing: off
  flowtype/object-type-delimiter: off
  flowtype/semi: off
  flowtype/space-after-type-colon: off
  flowtype/space-before-generic-bracket: off
  flowtype/space-before-type-colon: off
  flowtype/union-intersection-spacing: off
