include:
  - 'src/'
exclude:
  - 'src/polyfills'
clean: true
extends: '@istanbuljs/nyc-config-typescript'
temp-directory: 'coverage/tests'
report-dir: 'coverage/tests'
skip-full: true
reporter: [json, html, text]
