# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: ubuntu_node_12

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'

      - script: |
          npm ci && npm testonly
        displayName: 'npm ci && npm testonly'

  - job: ubuntu_node_10

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm ci && npm test:ci
        displayName: 'npm ci && npm test:ci'

  - job: ubuntu_node_8

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          npm install && npm testonly
        displayName: 'npm install && npm testonly'

  - job: ubuntu_node_6

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '6.x'
        displayName: 'Install Node.js'

      - script: |
          npm install && npm testonly
        displayName: 'npm install && npm testonly'
